app/models.py
from datetime import datetime
from flask_login import UserMixin
from werkzeug.security import check_password_hash, generate_password_hash
from hashlib import md5
from app.extensions import db, login_manager


class User(UserMixin, db.Model):
    id = db.Column(db.Integer, primary_key=True)
    first_name = db.Column(db.String(64), index=True, unique=True)
    last_name = db.Column(db.String(64), index=True, unique=True)
    username = db.Column(db.String(64), index=True, unique=True)
    email = db.Column(db.String(120), index=True, unique=True)
    password_hash = db.Column(db.String(128))
    posts = db.relationship("Post", backref="author", lazy="dynamic")
    about_me = db.Column(db.String(140))
    last_seen = db.Column(db.DateTime, default=datetime.now)

    def __repr__(self):
        return "<User {}>".format(self.username)

    def set_password_hash(self, password):
        self.password_hash = generate_password_hash(password)

    def check_password(self, password):
        return check_password_hash(self.password_hash, password)

    def avatar(self, size):
        digest = md5(self.email.lower().encode("utf-8")).hexdigest()
        return "https://www.gravatar.com/avatar/{}?d=identicon&s={}".format(
            digest, size
        )

    def save(self):
        db.session.add(self)
        db.session.commit()


# User Loader function
@login_manager.user_loader
def load_user(id):
    return User.query.get(int(id))


class Post(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    body = db.Column(db.String(140))
    timestamp = db.Column(db.DateTime, index=True, default=datetime.now)
    user_id = db.Column(db.Integer, db.ForeignKey("user.id"))

    def __repr__(self):
        return "<Post {}>".format(self.body)

app/forms.py
from flask_wtf import FlaskForm
from wtforms import (
    StringField,
    PasswordField,
    EmailField,
    BooleanField,
    SubmitField,
    TextAreaField,
)
from wtforms.validators import DataRequired, EqualTo, Email, ValidationError, Length

from app.models import User


class LoginForm(FlaskForm):
    username = StringField(label="Username", validators=[DataRequired()])
    password = PasswordField(label="Password", validators=[DataRequired()])
    remember_me = BooleanField(label="Remember Me", validators=[DataRequired()])
    submit = SubmitField(label="Login")


class RegistrationForm(FlaskForm):
    first_name = StringField(label="First Name", validators=[DataRequired()])
    last_name = StringField(label="Last Name", validators=[DataRequired()])
    username = StringField(label="Username", validators=[DataRequired()])
    email = EmailField(label="Email Address", validators=[DataRequired(), Email()])
    password = PasswordField(label="Password", validators=[DataRequired()])
    conf_password = PasswordField(
        label="Confirm Password",
        validators=[DataRequired(), EqualTo("password", "Password did not match")],
    )
    submit = SubmitField(label="Register")

    def validate_username(self, username):
        user = User.query.filter_by(username=username.data).first()
        if user is not None:
            raise ValidationError("Please use a different username.")

    def validate_email(self, email):
        user = User.query.filter_by(email=email.data).first()
        if user is not None:
            raise ValidationError("Please use a different email address.")


# Profile Edit Form
class ProfileEditForm(FlaskForm):
    first_name = StringField(label="First Name", validators=[DataRequired()])
    last_name = StringField(label="Last Name", validators=[DataRequired()])
    username = StringField(label="Username", validators=[DataRequired()])
    email = EmailField(label="Email Address", validators=[DataRequired(), Email()])
    about_me = TextAreaField("About Me", validators=[Length(min=0, max=140)])
    submit = SubmitField(label="Update")

app/__init__.py
from flask import Flask
from app.extensions import *


def create_app(config_class=None) -> Flask:
    """
    Create and configure an instance of the Flask application.
    Args:
        config_class (optional): The configuration class to use for the application.
                                 If None, the default configuration will be used.
    Returns:
        Flask: The configured Flask application instance.
    """

    # Create a Flask instance
    app = Flask(__name__)

    # Load Configurations
    if config_class:
        app.config.from_object(config_class)
    else:
        app.config.from_object("app.config.Config")

    # Bind the app with Extensions
    db.init_app(app)
    migrate.init_app(app, db)
    login_manager.init_app(app)

    from app import models

    # Import and Register blueprints
    from app.routes import root_bp

    app.register_blueprint(root_bp)

    # Return Flask instance
    return app

app/routes.py
from datetime import datetime
from flask import render_template, flash, redirect, url_for, request
from flask import Blueprint
from flask_login import current_user, login_user, logout_user, login_required

from app.forms import LoginForm, RegistrationForm, ProfileEditForm
from app.models import User
from app.extensions import db


# Root Blueprint
root_bp = Blueprint("root", __name__)


# Index Route
@root_bp.route("/")
@root_bp.route("/index")
@login_required
def index():
    return render_template(template_name_or_list="index.html", title="Home")


# Login route
@root_bp.route("/login", methods=["GET", "POST"])
def login():

    if current_user.is_authenticated:
        return redirect(url_for("root.index"))

    form = LoginForm()

    if form.validate_on_submit():

        user = User.query.filter_by(username=form.username.data).first()

        if user is None or not user.check_password(form.password.data):
            flash("Invalid username or password")
            return redirect(url_for("root.login"))

        login_user(user, remember=form.remember_me.data)

        return redirect(url_for("root.dashboard"))

    return render_template("auth/login.html", form=form)


# Login route
@root_bp.route("/register", methods=["GET", "POST"])
def register():
    form = RegistrationForm()

    if form.validate_on_submit():

        first_name = form.first_name.data
        last_name = form.last_name.data
        username = form.username.data
        email = form.email.data
        password = form.password.data

        user = User(
            first_name=first_name, last_name=last_name, email=email, username=username
        )

        user.set_password_hash(password)

        # Save the user in DB
        user.save()

        flash("User registered successfully")

        return redirect(url_for("root.login"))

    return render_template("auth/register.html", form=form)


# Logout Route
@root_bp.route("/logout")
def logout():
    logout_user()
    return redirect(url_for("root.index"))


# Dashboard Route
@root_bp.route("/dashboard")
@login_required
def dashboard():
    return render_template("dashboard.html")


# User Route
@root_bp.route("/user/<string:username>")
@login_required
def user(username: str):
    user = User.query.filter_by(username=username).first_or_404()

    posts = [
        {"author": user, "body": "Test post #1"},
        {"author": user, "body": "Test post #2"},
    ]
    return render_template("user.html", user=user, posts=posts)


# Edit Profile route
@root_bp.route("/edit_profile", methods=["GET", "POST"])
@login_required
def edit_profile():
    form = ProfileEditForm()

    if form.validate_on_submit():

        current_user.first_name = form.first_name.data
        current_user.last_name = form.last_name.data
        current_user.username = form.username.data
        current_user.email = form.email.data
        current_user.about_me = form.about_me.data

        db.session.commit()

        flash("Profile updated successfully")
        return redirect(url_for("root.edit_profile"))

    elif request.method == "GET":
        form.first_name.data = current_user.first_name
        form.last_name.data = current_user.last_name
        form.username.data = current_user.username
        form.email.data = current_user.email
        form.about_me.data = current_user.about_me

    return render_template("profile/edit.html", form=form)


@root_bp.before_request
def before_request():
    if current_user.is_authenticated:
        current_user.last_seen = datetime.now()
        db.session.commit()

app/templates/dashboard.html
{% extends "layouts/_base.html" %}

{% block title %}Dashboard{% endblock %}

{% block content %}
    <h1>Dashboard</h1>
{% endblock %}

app/templates/includes/_posts.html
<table>
    <tr valign="top">
        <td><img src="{{ post.author.avatar(36) }}"></td>
        <td>{{ post.author.username }} says:<br>{{ post.body }}</td>
    </tr>
</table>

app/templates/index.html
{% extends "layouts/_base.html" %}

{% block title %}Home{% endblock %}

{% block content %}
    <h1>Hello {{ current_user.username }}</h1>
{% endblock %}

app/templates/layouts/_base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %} - Flask</title>
</head>
<body>
    <div>Microblog: 
        <a href="{{ url_for('root.index') }}">Home</a>
        {% if current_user.is_anonymous %}
        <a href="{{ url_for('root.login') }}">Login</a>
        <a href="{{ url_for('root.register') }}">Register</a>
        {% else %}
        <a href="{{ url_for('root.dashboard') }}">Dashboard</a>
        <a href="{{ url_for('root.user', username=current_user.username) }}">Profile</a>
        <a href="{{ url_for('root.logout') }}">Logout</a>
        {% endif %}
    </div>
    
    <hr>
    
    <br>
    {% with messages = get_flashed_messages() %}
    {% if messages %}
    <ul>
        {% for message in messages %}
        <li>{{ message }}</li>
        {% endfor %}
    </ul>
    {% endif %}
    {% endwith %}
    <br>

    {% block content %}{% endblock %}
</body>
</html>

app/templates/profile/edit.html
{% extends "layouts/_base.html" %}

{% block title %}Edit Profile{% endblock %}

{% block content %}
    <div class="edit_profile-form">
        <form method="post" novalidate>
            {{ form.hidden_tag() }}

            <!----------- First Name ---------->
            <p>
                {{ form.first_name.label }}<br>
                {{ form.first_name(size=32) }}
                {% for error in form.first_name.errors %}
                    <span style="color: red;">[{{ error }}]</span>
                {% endfor %}
            </p>

            <!----------- Last Name ---------->
            <p>
                {{ form.last_name.label }}<br>
                {{ form.last_name(size=32) }}
                {% for error in form.last_name.errors %}
                    <span style="color: red;">[{{ error }}]</span>
                {% endfor %}
            </p>

            <!----------- Username ---------->
            <p>
                {{ form.username.label }}<br>
                {{ form.username(size=32) }}
                {% for error in form.username.errors %}
                    <span style="color: red;">[{{ error }}]</span>
                {% endfor %}
            </p>

            <!----------- Email ---------->
            <p>
                {{ form.email.label }}<br>
                {{ form.email(size=32) }}
                {% for error in form.email.errors %}
                    <span style="color: red;">[{{ error }}]</span>
                {% endfor %}
            </p>

            <!----------- About Me ---------->
            <p>
                {{ form.about_me.label }}<br>
                {{ form.about_me(cols=50, rows=5) }}
                {% for error in form.about_me.errors %}
                    <span style="color: red;">[{{ error }}]</span>
                {% endfor %}
            </p>


            <!----------- Submit ---------->
            <p>{{ form.submit() }}</p>
        </form>
    </div>
{% endblock %}

app/templates/user.html
{% extends "layouts/_base.html" %}

{% block title %}User Page{% endblock %}

{% block content %}
    <table>
        <tr valign="top">
            <td><img src="{{ user.avatar(128) }}"></td>
            <td>
                <h1>User: {{ user.username }}</h1>
                {% if user.about_me %}<p>About Me : {{ user.about_me }}</p>{% endif %}
                {% if user.last_seen %}<p>Last Seen : {{ user.last_seen }}</p>{% endif %}
                <a href="{{ url_for('root.edit_profile') }}">EDIT</a>
            </td>
        </tr>
    </table>
    <hr>
    {% for post in posts %}
        {% include "includes/_posts.html" %}
    {% endfor %}
{% endblock %}